[env:windows_x86]
platform = https://github.com/JAQUBA/JQB_MinGW.git
extra_scripts =
    post:scripts/copy_fonts.py
lib_deps =
    ../JQB_WindowsLib
    ../JQB_CAMCommon
lib_extra_dirs =
    lib/Clipper2/CPP
